[meta]
author = "Karl"
name = "Ur"
version = "1"
date = "2025-10-12"

[outer_boarder]
height_top = 20 
height_bottom = 20
width_left = 20
width_right = 20
colour = "#19DBFF"

[inner_boarder]
height_top = 20
height_bottom = 20
width_left = 20
width_right = 20
colour = "#0C88A3"

[grid]
cells_horizontal = 8
cells_vertical = 3

width_of_cell = [
    100,
    100,
    100,
    100,
    100,
    100,
    100,
    100,
]
height_of_cell = [
    100,
    100,
    100,
]
vertical_gutter= [
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
]
horizontal_gutter= [
    1,
    1,
    1,
    1,
]
colour_of_cell = [
    [
        "#2686B9",
        "#2686B9",
        "#2686B9",
        "#2686B9",
        "#0C88A3",
        "#0C88A3",
        "#2686B9",
        "#2686B9",
    ],
    [
        "#2686B9",
        "#2686B9",
        "#2686B9",
        "#2686B9",
        "#2686B9",
        "#2686B9",
        "#2686B9",
        "#2686B9",
    ],
    [
        "#2686B9",
        "#2686B9",
        "#2686B9",
        "#2686B9",
        "#0C88A3",
        "#0C88A3",
        "#2686B9",
        "#2686B9",
    ],
]

[tokens]
token_1 = "_light.png"
token_2 = "_dark.png"

[[cell_decorator]]
name = "_flower.png"
coords = [[0,0], [0,6], [1,3], [2,0], [2,6]]
