[meta]
author = "Karl"
name = "Hnefatafl"
version = "1"
date = "2025-10-12"

[outer_boarder]
height_top = 30 
height_bottom = 30
width_left = 30
width_right = 30
colour = "#543013"

[inner_boarder]
height_top = 5
height_bottom = 5
width_left = 5
width_right = 5
colour = "#744628"

[grid]
cells_horizontal = 11
cells_vertical = 11
width_of_cell = [
    60,
    60,
    60,
    60,
    60,
    60,
    60,
    60,
    60,
    60,
    60,
]
height_of_cell = [
    60,
    60,
    60,
    60,
    60,
    60,
    60,
    60,
    60,
    60,
    60,
]
vertical_gutter= [
    2,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    2,
]
horizontal_gutter= [
    2,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    2,
]
colour_of_cell = [
    [
        "#744628",
        "#744628",
        "#744628",
        "#543013",
        "#543013",
        "#543013",
        "#543013",
        "#543013",
        "#744628",
        "#744628",
        "#744628",
    ],
    [
        "#744628",
        "#744628",
        "#744628",
        "#744628",
        "#744628",
        "#543013",
        "#744628",
        "#744628",
        "#744628",
        "#744628",
        "#744628",
    ],
    [
        "#744628",
        "#744628",
        "#744628",
        "#744628",
        "#744628",
        "#744628",
        "#744628",
        "#744628",
        "#744628",
        "#744628",
        "#744628",
    ],
    [
        "#543013",
        "#744628",
        "#744628",
        "#744628",
        "#744628",
        "#543013",
        "#744628",
        "#744628",
        "#744628",
        "#744628",
        "#543013",
    ],
    [
        "#543013",
        "#744628",
        "#744628",
        "#744628",
        "#543013",
        "#543013",
        "#543013",
        "#744628",
        "#744628",
        "#744628",
        "#543013",
    ],
    [
        "#543013",
        "#543013",
        "#744628",
        "#543013",
        "#543013",
        "#543013",
        "#543013",
        "#543013",
        "#744628",
        "#543013",
        "#543013",
    ],
    [
        "#543013",
        "#744628",
        "#744628",
        "#744628",
        "#543013",
        "#543013",
        "#543013",
        "#744628",
        "#744628",
        "#744628",
        "#543013",
    ],
    [
        "#543013",
        "#744628",
        "#744628",
        "#744628",
        "#744628",
        "#543013",
        "#744628",
        "#744628",
        "#744628",
        "#744628",
        "#543013",
    ],
    [
        "#744628",
        "#744628",
        "#744628",
        "#744628",
        "#744628",
        "#744628",
        "#744628",
        "#744628",
        "#744628",
        "#744628",
        "#744628",
    ],
    [
        "#744628",
        "#744628",
        "#744628",
        "#744628",
        "#744628",
        "#543013",
        "#744628",
        "#744628",
        "#744628",
        "#744628",
        "#744628",
    ],
    [
        "#744628",
        "#744628",
        "#744628",
        "#543013",
        "#543013",
        "#543013",
        "#543013",
        "#543013",
        "#744628",
        "#744628",
        "#744628",
    ],
]

[token_images]
A = "_attacker.png"
D = "_defender.png"
K = "_king.png"

[[cell_decorator]]
name = "_corner_space.png"
coords = [[0, 0], [10, 0], [0, 10], [10, 10]]

[[cell_decorator]]
name = "_kings_space.png"
coords = [[5, 5]]

[[initial_state]]
token = "A"
coords = [[0, 3],[0, 4],[0, 5],[0, 6],[0, 7],[1, 5], [10, 3],[10, 4],[10, 5],[10, 6],[10, 7],[9, 5], [3, 0],[3, 10],[4, 0],[4, 10],[5, 0],[5, 10],[6, 0],[6, 10],[7, 0],[7, 10],[5, 1],[5, 9]]

[[initial_state]]
token = "D"
coords = [[3, 5],[4, 4],[4, 5],[4, 6],[5, 3],[5, 4],[5, 6],[5, 7],[6, 4],[6, 5],[6, 6],[7, 5]]

[[initial_state]]
token = "K"
coords = [[5, 5]]