# pylint: skip-file

from typing import Optional, Tuple

from pygame_board.gb_definition import Gameboard

def height_of_row(gb: Gameboard, row: int) -> int: ...
def height_of_rows(gb: Gameboard) -> int: ...
def height_of_inner_board(gb: Gameboard) -> int: ...
def height_of_outer_board(gb: Gameboard) -> int: ...
def width_of_column(gb: Gameboard, column: int) -> int: ...
def width_of_columns(gb: Gameboard) -> int: ...
def width_of_inner_board(gb: Gameboard) -> int: ...
def width_of_outer_board(gb: Gameboard) -> int: ...
def total_board_size(gb: Gameboard) -> Tuple[int, int]: ...
def absolute_position_of_cell(gb: Gameboard, row: int, col: int) -> Tuple[int, int]: ...
def cell_at_absolute_coordinates(
    gb: Gameboard, x: int, y: int
) -> Optional[Tuple[int, int]]: ...
