# pylint: skip-file

from typing import Dict, Optional, Tuple

import pygame

from pygame_board.gb_definition import Gameboard

image_cache: Dict[str, pygame.Surface]

def get_cached_image(
    _filename: str, size: Optional[Tuple[int, int]] = None
) -> "pygame.Surface": ...
def draw_outer_border(gb: Gameboard, surface: pygame.Surface) -> None: ...
def draw_inner_border(gb: Gameboard, surface: pygame.Surface) -> None: ...
def draw_cell_area(gb: Gameboard, surface: pygame.Surface) -> None: ...
def draw_cells(gb: Gameboard, surface: pygame.Surface) -> None: ...
def draw_cell_decorator(
    gb: Gameboard, surface: pygame.Surface, decorator_name: str, row: int, col: int
) -> None: ...
def draw_board_decorator(
    gb: Gameboard, surface: pygame.Surface, decorator_name: str, x: int, y: int
) -> None: ...
def draw_gameboard(gb: Gameboard) -> pygame.Surface: ...
