# pylint: skip-file

from typing import Dict, Tuple

import pygame

from pygame_board.gb_definition import Gameboard

_token_positions: Dict[Tuple[int, int], str]

def draw_token(
    gb: Gameboard, surface: pygame.Surface, token: str, row: int, col: int
) -> None: ...
def draw_tokens(gb: Gameboard, surface: pygame.Surface) -> None: ...
def place_token(token: str, row: int, col: int) -> bool: ...
def move_token(from_row: int, from_col: int, to_row: int, to_col: int) -> bool: ...
def remove_token(row: int, col: int) -> bool: ...
def clear_tokens() -> None: ...
def set_initial_state(gb: Gameboard, surface: pygame.Surface) -> None: ...
def extract_token_map(gb: Gameboard) -> list[list[str]]: ...
def print_token_map(gb: Gameboard) -> None: ...
