[meta]
author = "Karl"
name = "Checkers"
version = "1"
date = "2025-10-12"

[outer_boarder]
height_top = 10
height_bottom = 10
width_left = 10
width_right = 10
colour = "#076C72"

[inner_boarder]
height_top = 10
height_bottom = 10
width_left = 10
width_right = 10
colour = "#0394A6"

[grid]
cells_horizontal = 8
cells_vertical = 8
width_of_cell = [
    80,
    80,
    80,
    80,
    80,
    80,
    80,
    80,
]
height_of_cell = [
    80,
    80,
    80,
    80,
    80,
    80,
    80,
    80,
]
vertical_gutter= [
    2,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    2,
]
horizontal_gutter= [
    2,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    2,
]
colour_of_cell = [
    [
        "#0394A6",
        "#076C72",
        "#0394A6",
        "#076C72",
        "#0394A6",
        "#076C72",
        "#0394A6",
        "#076C72",
    ],
    [
        "#076C72",
        "#0394A6",
        "#076C72",
        "#0394A6",
        "#076C72",
        "#0394A6",
        "#076C72",
        "#0394A6",
    ],    
    [
        "#0394A6",
        "#076C72",
        "#0394A6",
        "#076C72",
        "#0394A6",
        "#076C72",
        "#0394A6",
        "#076C72",
    ],
    [
        "#076C72",
        "#0394A6",
        "#076C72",
        "#0394A6",
        "#076C72",
        "#0394A6",
        "#076C72",
        "#0394A6",
    ],    
    [
        "#0394A6",
        "#076C72",
        "#0394A6",
        "#076C72",
        "#0394A6",
        "#076C72",
        "#0394A6",
        "#076C72",
    ],
    [
        "#076C72",
        "#0394A6",
        "#076C72",
        "#0394A6",
        "#076C72",
        "#0394A6",
        "#076C72",
        "#0394A6",
    ],    
    [
        "#0394A6",
        "#076C72",
        "#0394A6",
        "#076C72",
        "#0394A6",
        "#076C72",
        "#0394A6",
        "#076C72",
    ],
    [
        "#076C72",
        "#0394A6",
        "#076C72",
        "#0394A6",
        "#076C72",
        "#0394A6",
        "#076C72",
        "#0394A6",
    ],
]

[token_images]
light = "_light.png"
dark = "_dark.png"

[[initial_state]]
token = "light"
coords = [[0, 1],[0, 3],[0, 5],[0, 7],[1, 0],[1, 2],[1, 4],[1, 6],[2, 1],[2, 3],[2, 5],[2, 7]]

[[initial_state]]
token = "dark"
coords = [[5, 0],[5, 2],[5, 4],[5, 6],[6, 1],[6, 3],[6, 5],[6, 7],[7, 0],[7, 2],[7, 4],[7, 6]]